### ISSUE TITLE
请问大佬有考虑开源吗？

### ISSUE THREAD

**Issue by wd2010** [deyihu/mdpress#1]
大佬，请问有考虑开源吗？或者要实现这个网站有哪些参考的资料？我是一名前端开发，发现这个项目很有意思，想学习一下，谢谢

**Comment by deyihu** [comment]
主要是一个markdown编辑器，其他的就是简单的crud了，将文档保存后，在服务端起个vitepress,执行vitepress编译命令即可
https://github.com/deyihu/mdpress-editor

**Comment by Cenergy** [comment]
大佬，请问有考虑开源吗？这个项目结合vitepress也太好了吧
